apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/poly-glot/personal-cloud//deployment/base/?ref=main

namespace: pakistan-2003
namePrefix: main-

patches:
- path: deployment.yaml
- path: ingress.yaml
- patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/env/0
    - op: remove
      path: /spec/template/spec/containers/0/envFrom/0
  target:
    kind: Deployment
    name: webapp

images:
- name: webapp:latest
  newName: lhr.ocir.io/lrhvckxzwf3l/pakistan-2003
  newTag: 1b4b88281c5ea75685ee6e1b197d14cb20839863
